[build]
  publish = "public"
  command = "hugo --gc --minify -mod=mod"

  [build.environment]
    HUGO_VERSION = "0.113.0"
    HUGO_ENABLEGITINFO = "true"
    GO_VERSION = "1.18"

[context.deploy-preview]
  command = "hugo --gc --minify -mod=mod --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -mod=mod -b $DEPLOY_PRIME_URL"
